/**
 * Product Specifications Configuration
 * Defines dynamic form fields for each product category and subcategory
 */

export interface SpecField {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'textarea' | 'checkbox';
  placeholder?: string;
  required?: boolean;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  step?: number;
  helpText?: string;
}

export interface CategorySpecs {
  [subcategory: string]: SpecField[];
}

export interface AllSpecs {
  [category: string]: CategorySpecs;
}

export const PRODUCT_SPECIFICATIONS: AllSpecs = {
  electronics: {
    mobile_phones: [
      {
        name: 'memory_storage',
        label: 'Storage Memory',
        type: 'select',
        required: true,
        placeholder: 'Select storage capacity',
        options: [
          { value: '32GB', label: '32GB' },
          { value: '64GB', label: '64GB' },
          { value: '128GB', label: '128GB' },
          { value: '256GB', label: '256GB' },
          { value: '512GB', label: '512GB' },
          { value: '1TB', label: '1TB' },
        ],
        helpText: 'Internal storage capacity',
      },
      {
        name: 'ram',
        label: 'RAM Memory',
        type: 'select',
        required: true,
        placeholder: 'Select RAM',
        options: [
          { value: '2GB', label: '2GB' },
          { value: '3GB', label: '3GB' },
          { value: '4GB', label: '4GB' },
          { value: '6GB', label: '6GB' },
          { value: '8GB', label: '8GB' },
          { value: '12GB', label: '12GB' },
          { value: '16GB', label: '16GB' },
        ],
        helpText: 'RAM memory size',
      },
      {
        name: 'processor',
        label: 'Processor/Chipset',
        type: 'text',
        required: true,
        placeholder: 'e.g., Snapdragon 8 Gen 1, Apple A16 Bionic',
        helpText: 'Phone processor or chipset',
      },
      {
        name: 'display_size',
        label: 'Display Size',
        type: 'text',
        required: true,
        placeholder: 'e.g., 6.1 inches',
        helpText: 'Screen diagonal size in inches',
      },
      {
        name: 'display_type',
        label: 'Display Type',
        type: 'select',
        required: true,
        placeholder: 'Select display type',
        options: [
          { value: 'IPS LCD', label: 'IPS LCD' },
          { value: 'AMOLED', label: 'AMOLED' },
          { value: 'OLED', label: 'OLED' },
          { value: 'LCD', label: 'LCD' },
          { value: 'Retina Display', label: 'Retina Display' },
        ],
      },
      {
        name: 'refresh_rate',
        label: 'Refresh Rate',
        type: 'select',
        placeholder: 'Select refresh rate',
        options: [
          { value: '60Hz', label: '60Hz' },
          { value: '90Hz', label: '90Hz' },
          { value: '120Hz', label: '120Hz' },
          { value: '144Hz', label: '144Hz' },
          { value: '165Hz', label: '165Hz' },
        ],
      },
      {
        name: 'rear_camera',
        label: 'Rear Camera',
        type: 'text',
        required: true,
        placeholder: 'e.g., 48MP + 12MP + 12MP',
        helpText: 'Main camera specifications',
      },
      {
        name: 'front_camera',
        label: 'Front Camera',
        type: 'text',
        required: true,
        placeholder: 'e.g., 12MP',
        helpText: 'Selfie camera specifications',
      },
      {
        name: 'battery_capacity',
        label: 'Battery Capacity',
        type: 'text',
        required: true,
        placeholder: 'e.g., 4500mAh',
        helpText: 'Battery capacity in mAh',
      },
      {
        name: 'charging',
        label: 'Charging Technology',
        type: 'text',
        placeholder: 'e.g., 65W Fast Charging, Wireless Charging',
        helpText: 'Charging speed and type',
      },
      {
        name: 'operating_system',
        label: 'Operating System',
        type: 'select',
        required: true,
        placeholder: 'Select OS',
        options: [
          { value: 'Android', label: 'Android' },
          { value: 'iOS', label: 'iOS' },
          { value: 'Custom Android', label: 'Custom Android' },
        ],
      },
      {
        name: 'sim_slots',
        label: 'SIM Slots',
        type: 'select',
        placeholder: 'Select SIM configuration',
        options: [
          { value: 'Single SIM', label: 'Single SIM' },
          { value: 'Dual SIM', label: 'Dual SIM' },
          { value: 'Nano SIM', label: 'Nano SIM' },
          { value: 'eSIM', label: 'eSIM' },
        ],
      },
      {
        name: 'water_resistance',
        label: 'Water Resistance',
        type: 'select',
        placeholder: 'Select water resistance rating',
        options: [
          { value: 'IP67', label: 'IP67 (Dust & Water resistant)' },
          { value: 'IP68', label: 'IP68 (Dust & Water resistant)' },
          { value: 'None', label: 'None' },
        ],
      },
      {
        name: 'warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
      {
        name: 'model_number',
        label: 'Model Number',
        type: 'text',
        required: true,
        placeholder: 'e.g., SM-A135F, iPhone14,5',
        helpText: 'Exact model number (find on phone or box)',
      },
      {
        name: 'color',
        label: 'Color',
        type: 'text',
        required: true,
        placeholder: 'e.g., Midnight Black, Starlight White, Sierra Blue',
        helpText: 'Phone color variant',
      },
      {
        name: 'network_type',
        label: 'Network Type',
        type: 'select',
        required: true,
        placeholder: 'Select network type',
        options: [
          { value: '2G (GSM)', label: '2G (GSM)' },
          { value: '3G (UMTS/HSPA)', label: '3G (UMTS/HSPA)' },
          { value: '4G (LTE)', label: '4G (LTE)' },
          { value: '5G', label: '5G' },
          { value: '4G + 5G', label: '4G + 5G' },
        ],
        helpText: 'Network connectivity support',
      },
      {
        name: 'condition_details',
        label: 'Condition Details (for Used Phones)',
        type: 'textarea',
        placeholder: 'Describe condition: scratches, dents, battery health, screen condition, etc.',
        helpText: 'Important for used/refurbished phones - describe any damage or wear',
      },
      {
        name: 'imei_confirmed',
        label: 'IMEI Confirmation',
        type: 'checkbox',
        helpText: 'Check if you have verified the IMEI number matches the device',
      },
    ],
    laptops: [
      {
        name: 'processor',
        label: 'Processor',
        type: 'text',
        required: true,
        placeholder: 'e.g., Intel Core i9-13th Gen, Apple M2 Max',
        helpText: 'CPU model and generation',
      },
      {
        name: 'processor_cores',
        label: 'Processor Cores',
        type: 'select',
        required: true,
        placeholder: 'Select core count',
        options: [
          { value: '2', label: '2 Cores (Dual)' },
          { value: '4', label: '4 Cores (Quad)' },
          { value: '6', label: '6 Cores (Hexa)' },
          { value: '8', label: '8 Cores (Octa)' },
          { value: '10', label: '10 Cores' },
          { value: '12', label: '12 Cores' },
          { value: '16', label: '16 Cores' },
          { value: '20', label: '20 Cores' },
          { value: '24+', label: '24+ Cores' },
        ],
        helpText: 'Number of processor cores',
      },
      {
        name: 'ram',
        label: 'RAM Memory',
        type: 'select',
        required: true,
        placeholder: 'Select RAM',
        options: [
          { value: '4GB', label: '4GB' },
          { value: '8GB', label: '8GB' },
          { value: '16GB', label: '16GB' },
          { value: '32GB', label: '32GB' },
          { value: '64GB', label: '64GB' },
        ],
      },
      {
        name: 'storage_type',
        label: 'Storage Type',
        type: 'select',
        required: true,
        placeholder: 'Select storage type',
        options: [
          { value: 'HDD', label: 'HDD (Hard Disk Drive)' },
          { value: 'SSD', label: 'SSD (Solid State Drive)' },
          { value: 'NVMe SSD', label: 'NVMe SSD (Ultra-fast)' },
          { value: 'Hybrid', label: 'Hybrid (HDD + SSD)' },
        ],
      },
      {
        name: 'storage_capacity',
        label: 'Storage Capacity',
        type: 'select',
        required: true,
        placeholder: 'Select storage size',
        options: [
          { value: '128GB', label: '128GB' },
          { value: '256GB', label: '256GB' },
          { value: '512GB', label: '512GB' },
          { value: '1TB', label: '1TB' },
          { value: '2TB', label: '2TB' },
          { value: '4TB', label: '4TB' },
        ],
      },
      {
        name: 'graphics_card',
        label: 'Graphics Card',
        type: 'text',
        placeholder: 'e.g., NVIDIA RTX 4090, Intel Iris Xe',
        helpText: 'GPU model and VRAM if available',
      },
      {
        name: 'graphics_card_type',
        label: 'Graphics Type',
        type: 'select',
        placeholder: 'Select graphics type',
        options: [
          { value: 'Integrated', label: 'Integrated GPU' },
          { value: 'Dedicated', label: 'Dedicated GPU' },
          { value: 'Hybrid', label: 'Hybrid (Integrated + Dedicated)' },
        ],
        helpText: 'Integrated, Dedicated, or Hybrid graphics',
      },
      {
        name: 'display_size',
        label: 'Display Size',
        type: 'text',
        required: true,
        placeholder: 'e.g., 15.6 inches, 14"',
        helpText: 'Screen diagonal size in inches',
      },
      {
        name: 'display_resolution',
        label: 'Display Resolution',
        type: 'select',
        required: true,
        placeholder: 'Select resolution',
        options: [
          { value: '720p', label: '720p (HD)' },
          { value: '1080p', label: '1080p (Full HD)' },
          { value: '1440p', label: '1440p (QHD)' },
          { value: '2K', label: '2K' },
          { value: '4K', label: '4K (Ultra HD)' },
          { value: 'Retina', label: 'Retina Display' },
        ],
        helpText: 'Screen resolution quality',
      },
      {
        name: 'refresh_rate',
        label: 'Refresh Rate',
        type: 'select',
        placeholder: 'Select refresh rate',
        options: [
          { value: '60Hz', label: '60Hz' },
          { value: '90Hz', label: '90Hz' },
          { value: '120Hz', label: '120Hz' },
          { value: '144Hz', label: '144Hz' },
          { value: '165Hz', label: '165Hz' },
          { value: '240Hz', label: '240Hz' },
        ],
      },
      {
        name: 'product_condition',
        label: 'Product Condition',
        type: 'select',
        required: true,
        placeholder: 'Select condition',
        options: [
          { value: 'Brand New', label: 'Brand New' },
          { value: 'Used - Fairly Used', label: 'Used - Fairly Used' },
          { value: 'Refurbished', label: 'Refurbished' },
        ],
        helpText: 'Select product condition - will show grading options if used',
      },
      {
        name: 'condition_grade',
        label: 'Condition Grade',
        type: 'select',
        placeholder: 'Select grade',
        options: [
          { value: 'Grade A', label: 'Grade A (Excellent - Minor wear)' },
          { value: 'Grade B', label: 'Grade B (Good - Moderate wear)' },
          { value: 'Grade C', label: 'Grade C (Fair - Heavy wear/scuffs)' },
        ],
        helpText: 'Only required for used/refurbished laptops',
      },
      {
        name: 'operating_system',
        label: 'Operating System',
        type: 'select',
        required: true,
        placeholder: 'Select OS',
        options: [
          { value: 'Windows 10', label: 'Windows 10' },
          { value: 'Windows 11', label: 'Windows 11' },
          { value: 'macOS', label: 'macOS' },
          { value: 'Linux', label: 'Linux' },
          { value: 'DOS / No OS', label: 'DOS / No OS' },
        ],
      },
      {
        name: 'battery_hours',
        label: 'Battery Life (Hours)',
        type: 'number',
        placeholder: 'e.g., 10',
        helpText: 'Approximate battery life in hours',
      },
      {
        name: 'weight_kg',
        label: 'Weight (kg)',
        type: 'number',
        placeholder: 'e.g., 1.8',
        step: 0.1,
        helpText: 'Weight in kilograms',
      },
      {
        name: 'wifi_version',
        label: 'Wi-Fi Version',
        type: 'select',
        placeholder: 'Select Wi-Fi standard',
        options: [
          { value: 'Wi-Fi 5 (802.11ac)', label: 'Wi-Fi 5 (802.11ac)' },
          { value: 'Wi-Fi 6 (802.11ax)', label: 'Wi-Fi 6 (802.11ax)' },
          { value: 'Wi-Fi 6E', label: 'Wi-Fi 6E' },
          { value: 'Wi-Fi 7', label: 'Wi-Fi 7' },
        ],
      },
      {
        name: 'bluetooth_version',
        label: 'Bluetooth Version',
        type: 'select',
        placeholder: 'Select Bluetooth version',
        options: [
          { value: 'Bluetooth 4.2', label: 'Bluetooth 4.2' },
          { value: 'Bluetooth 5.0', label: 'Bluetooth 5.0' },
          { value: 'Bluetooth 5.1', label: 'Bluetooth 5.1' },
          { value: 'Bluetooth 5.2', label: 'Bluetooth 5.2' },
          { value: 'Bluetooth 5.3', label: 'Bluetooth 5.3' },
          { value: 'Bluetooth 5.4', label: 'Bluetooth 5.4' },
        ],
      },
      {
        name: 'ports',
        label: 'Ports & Connectivity',
        type: 'textarea',
        placeholder: 'e.g., USB-C x2, HDMI 2.1, SD card reader, 3.5mm audio jack, Thunderbolt 4',
        helpText: 'List all available ports and connectivity options',
      },
      {
        name: 'webcam_quality',
        label: 'Webcam Quality',
        type: 'select',
        placeholder: 'Select webcam quality',
        options: [
          { value: 'None', label: 'None' },
          { value: '720p', label: '720p (HD)' },
          { value: '1080p', label: '1080p (Full HD)' },
          { value: '2K', label: '2K' },
          { value: '4K', label: '4K' },
        ],
      },
      {
        name: 'warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
      {
        name: 'integrity_confirmed',
        label: 'Integrity Confirmation',
        type: 'checkbox',
        required: true,
        helpText: 'I confirm this product is genuine, functional, and not stolen or illegally obtained',
      },
    ],
    cameras: [
      {
        name: 'camera_type',
        label: 'Camera Type',
        type: 'select',
        required: true,
        placeholder: 'Select camera type',
        options: [
          { value: 'DSLR', label: 'DSLR' },
          { value: 'Mirrorless', label: 'Mirrorless' },
          { value: 'Digital Compact', label: 'Digital Compact' },
          { value: 'Action Camera', label: 'Action Camera' },
          { value: 'Drone Camera', label: 'Drone Camera' },
          { value: 'Camcorder', label: 'Camcorder' },
          { value: 'CCTV / Security Camera', label: 'CCTV / Security Camera' },
        ],
      },
      {
        name: 'megapixels',
        label: 'Megapixels',
        type: 'number',
        required: true,
        placeholder: 'e.g., 24.2',
        step: 0.1,
        helpText: 'Camera sensor resolution in megapixels',
      },
      {
        name: 'sensor_size',
        label: 'Sensor Size',
        type: 'select',
        required: true,
        placeholder: 'Select sensor size',
        options: [
          { value: '1/2.3"', label: '1/2.3" (Compact)' },
          { value: '1"', label: '1" (Premium Compact)' },
          { value: 'Micro Four Thirds', label: 'Micro Four Thirds' },
          { value: 'APS-C', label: 'APS-C' },
          { value: 'Full Frame', label: 'Full Frame (35mm)' },
          { value: 'Super 35', label: 'Super 35' },
        ],
      },
      {
        name: 'iso_range',
        label: 'ISO Range',
        type: 'text',
        placeholder: 'e.g., 100–32000',
        helpText: 'ISO sensitivity range (native ISO)',
      },
      {
        name: 'aperture',
        label: 'Maximum Aperture',
        type: 'text',
        placeholder: 'e.g., f/1.8, f/2.8',
        helpText: 'For camera + lens bundle (widest aperture)',
      },
      {
        name: 'focal_length',
        label: 'Focal Length (Lens)',
        type: 'text',
        placeholder: 'e.g., 18–55mm, 24–70mm, or "Body Only"',
        helpText: 'Zoom range - indicate if camera body only',
      },
      {
        name: 'video_resolution',
        label: 'Video Resolution',
        type: 'select',
        placeholder: 'Select max video resolution',
        options: [
          { value: '1080p', label: '1080p (Full HD)' },
          { value: '4K', label: '4K (Ultra HD)' },
          { value: '5.3K', label: '5.3K' },
          { value: '8K', label: '8K' },
        ],
      },
      {
        name: 'autofocus_points',
        label: 'Autofocus Points',
        type: 'text',
        placeholder: 'e.g., 45, 567',
        helpText: 'Number of AF points (e.g., 45 AF points)',
      },
      {
        name: 'shutter_speed',
        label: 'Shutter Speed Range',
        type: 'text',
        placeholder: 'e.g., 1/8000 – 30 sec',
        helpText: 'Fastest to slowest shutter speed',
      },
      {
        name: 'connectivity',
        label: 'Connectivity',
        type: 'text',
        placeholder: 'e.g., Wi-Fi, Bluetooth, NFC, USB-C, HDMI',
        helpText: 'List all connectivity options',
      },
      {
        name: 'camera_battery_type',
        label: 'Battery Type',
        type: 'text',
        placeholder: 'e.g., LP-E17 Lithium-ion Rechargeable Battery',
        helpText: 'Battery model and specifications',
      },
      {
        name: 'camera_dimensions',
        label: 'Dimensions (W × H × D)',
        type: 'text',
        placeholder: 'e.g., 124 × 97 × 70 mm',
        helpText: 'Camera body dimensions in millimeters',
      },
      {
        name: 'weight_grams',
        label: 'Weight (grams)',
        type: 'number',
        placeholder: 'e.g., 450',
        helpText: 'Camera body weight in grams',
      },
      {
        name: 'product_condition',
        label: 'Product Condition',
        type: 'select',
        required: true,
        placeholder: 'Select condition',
        options: [
          { value: 'Brand New', label: 'Brand New' },
          { value: 'Used - Fairly Used', label: 'Used - Fairly Used' },
          { value: 'Refurbished', label: 'Refurbished' },
        ],
        helpText: 'Select product condition - will show grading options if used',
      },
      {
        name: 'condition_grade',
        label: 'Condition Grade',
        type: 'select',
        placeholder: 'Select grade',
        options: [
          { value: 'Grade A', label: 'Grade A (Excellent - Minor wear)' },
          { value: 'Grade B', label: 'Grade B (Good - Moderate wear)' },
          { value: 'Grade C', label: 'Grade C (Fair - Heavy wear/scuffs)' },
        ],
        helpText: 'Only required for used/refurbished cameras',
      },
      {
        name: 'memory_card_support',
        label: 'Memory Card Support',
        type: 'text',
        placeholder: 'e.g., SD, SDHC, SDXC, microSD',
        helpText: 'Supported memory card types',
      },
      {
        name: 'lens_mount',
        label: 'Lens Mount Type',
        type: 'text',
        placeholder: 'e.g., EF-M, Sony E-Mount, Nikon Z-Mount, Canon RF',
        helpText: 'Camera body lens mount (if applicable)',
      },
      {
        name: 'warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
      {
        name: 'integrity_confirmed',
        label: 'Integrity Confirmation',
        type: 'checkbox',
        required: true,
        helpText: 'I confirm this product is genuine, functional, and legally obtained',
      },
    ],
    headphones: [
      {
        name: 'headphone_type',
        label: 'Headphone Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Over-Ear', label: 'Over-Ear' },
          { value: 'On-Ear', label: 'On-Ear' },
          { value: 'In-Ear / Earbuds', label: 'In-Ear / Earbuds' },
          { value: 'Gaming Headset', label: 'Gaming Headset' },
          { value: 'Studio Monitoring', label: 'Studio Monitoring Headphones' },
        ],
        helpText: 'Select the type of headphones',
      },
      {
        name: 'connection_type',
        label: 'Connection Type',
        type: 'select',
        required: true,
        placeholder: 'Select connection',
        options: [
          { value: 'Wired (3.5mm)', label: 'Wired (3.5mm)' },
          { value: 'Wireless (Bluetooth)', label: 'Wireless (Bluetooth)' },
          { value: 'True Wireless (TWS)', label: 'True Wireless (TWS)' },
          { value: 'USB / USB-C', label: 'USB / USB-C' },
          { value: 'Dual Mode', label: 'Dual Mode (Wired + Wireless)' },
        ],
        helpText: 'How the headphones connect to devices',
      },
      {
        name: 'driver_size',
        label: 'Driver Size (mm)',
        type: 'text',
        placeholder: 'e.g., 40mm, 50mm',
        helpText: 'Speaker driver size in millimeters',
      },
      {
        name: 'headphone_frequency_response',
        label: 'Frequency Response',
        type: 'text',
        placeholder: 'e.g., 20Hz – 20kHz',
        helpText: 'Audio frequency range (Hz to Hz)',
      },
      {
        name: 'impedance',
        label: 'Impedance (Ohms)',
        type: 'text',
        placeholder: 'e.g., 32Ω, 64Ω',
        helpText: 'Electrical impedance rating',
      },
      {
        name: 'battery_hours',
        label: 'Battery Life (Hours)',
        type: 'number',
        placeholder: 'e.g., 30',
        helpText: 'Battery life (only for wireless/TWS)',
      },
      {
        name: 'headphone_charging_port',
        label: 'Charging Port',
        type: 'select',
        placeholder: 'Select charging port',
        options: [
          { value: 'USB-C', label: 'USB-C' },
          { value: 'Lightning', label: 'Lightning' },
          { value: 'Micro-USB', label: 'Micro-USB' },
          { value: 'Proprietary', label: 'Proprietary Connector' },
          { value: 'Not Applicable', label: 'N/A (Wired Only)' },
        ],
        helpText: 'Charging port type (optional for wired)',
      },
      {
        name: 'noise_cancellation',
        label: 'Noise Cancellation',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'None', label: 'None' },
          { value: 'Passive', label: 'Passive Noise Isolation' },
          { value: 'Active (ANC)', label: 'Active Noise Cancellation (ANC)' },
          { value: 'Hybrid', label: 'Hybrid ANC' },
        ],
        helpText: 'Noise cancellation capability',
      },
      {
        name: 'has_microphone',
        label: 'Microphone',
        type: 'select',
        required: true,
        placeholder: 'Select option',
        options: [
          { value: 'Yes', label: 'Yes - Built-in microphone' },
          { value: 'No', label: 'No - No microphone' },
        ],
        helpText: 'Important for gaming and calls',
      },
      {
        name: 'headphone_weight_grams',
        label: 'Weight (grams)',
        type: 'number',
        placeholder: 'e.g., 250',
        helpText: 'Headphone weight in grams',
      },
      {
        name: 'headphone_special_features',
        label: 'Special Features',
        type: 'textarea',
        placeholder: 'e.g., Transparency Mode, Dual Pairing, Fast Charging, Touch Controls',
        helpText: 'List any special features (optional)',
      },
      {
        name: 'water_resistance_rating',
        label: 'Water Resistance (IP Rating)',
        type: 'text',
        placeholder: 'e.g., IPX4, IPX5, IP67',
        helpText: 'Water/dust resistance rating (optional)',
      },
      {
        name: 'warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
    ],
    tablets: [
      {
        name: 'processor',
        label: 'Processor',
        type: 'text',
        required: true,
        placeholder: 'e.g., Apple M1, Snapdragon 8 Gen 1',
        helpText: 'Tablet processor model and generation',
      },
      {
        name: 'ram',
        label: 'RAM Memory',
        type: 'select',
        required: true,
        placeholder: 'Select RAM',
        options: [
          { value: '3GB', label: '3GB' },
          { value: '4GB', label: '4GB' },
          { value: '6GB', label: '6GB' },
          { value: '8GB', label: '8GB' },
          { value: '12GB', label: '12GB' },
        ],
      },
      {
        name: 'storage',
        label: 'Storage Capacity',
        type: 'select',
        required: true,
        placeholder: 'Select storage',
        options: [
          { value: '32GB', label: '32GB' },
          { value: '64GB', label: '64GB' },
          { value: '128GB', label: '128GB' },
          { value: '256GB', label: '256GB' },
          { value: '512GB', label: '512GB' },
          { value: '1TB', label: '1TB' },
        ],
      },
      {
        name: 'display_size',
        label: 'Display Size',
        type: 'text',
        required: true,
        placeholder: 'e.g., 10.9 inches, 11"',
        helpText: 'Screen diagonal size in inches',
      },
      {
        name: 'tablet_display_type',
        label: 'Display Type',
        type: 'select',
        placeholder: 'Select display type',
        options: [
          { value: 'LCD', label: 'LCD' },
          { value: 'IPS', label: 'IPS (In-Plane Switching)' },
          { value: 'AMOLED', label: 'AMOLED' },
          { value: 'Super AMOLED', label: 'Super AMOLED' },
          { value: 'Liquid Retina', label: 'Liquid Retina' },
        ],
      },
      {
        name: 'resolution',
        label: 'Display Resolution',
        type: 'text',
        placeholder: 'e.g., 2360 × 1640',
        helpText: 'Screen resolution in pixels',
      },
      {
        name: 'operating_system',
        label: 'Operating System',
        type: 'select',
        required: true,
        placeholder: 'Select OS',
        options: [
          { value: 'iPadOS', label: 'iPadOS' },
          { value: 'Android', label: 'Android' },
          { value: 'HarmonyOS', label: 'HarmonyOS' },
          { value: 'Windows', label: 'Windows' },
        ],
      },
      {
        name: 'battery_hours',
        label: 'Battery Life (Hours)',
        type: 'number',
        placeholder: 'e.g., 10',
        helpText: 'Approximate battery life in hours',
      },
      {
        name: 'connectivity',
        label: 'Connectivity',
        type: 'select',
        placeholder: 'Select connectivity type',
        options: [
          { value: 'Wi-Fi', label: 'Wi-Fi' },
          { value: 'Wi-Fi + LTE', label: 'Wi-Fi + LTE' },
          { value: 'Wi-Fi + 5G', label: 'Wi-Fi + 5G' },
          { value: 'Bluetooth', label: 'Bluetooth' },
          { value: 'USB-C', label: 'USB-C' },
        ],
        helpText: 'Available connectivity options',
      },
      {
        name: 'tablet_rear_camera',
        label: 'Rear Camera',
        type: 'text',
        placeholder: 'e.g., 12MP',
        helpText: 'Rear camera megapixels (optional)',
      },
      {
        name: 'tablet_front_camera',
        label: 'Front Camera',
        type: 'text',
        placeholder: 'e.g., 7MP, 12MP',
        helpText: 'Front camera megapixels (optional)',
      },
      {
        name: 'stylus_support',
        label: 'Stylus Support',
        type: 'select',
        placeholder: 'Select stylus type',
        options: [
          { value: 'None', label: 'None' },
          { value: 'Apple Pencil 1', label: 'Apple Pencil 1st Gen' },
          { value: 'Apple Pencil 2', label: 'Apple Pencil 2nd Gen' },
          { value: 'Apple Pencil Pro', label: 'Apple Pencil Pro' },
          { value: 'S-Pen', label: 'Samsung S-Pen' },
          { value: 'Other', label: 'Other Stylus' },
        ],
        helpText: 'Compatible stylus support',
      },
      {
        name: 'keyboard_compatible',
        label: 'Keyboard Compatibility',
        type: 'select',
        placeholder: 'Select option',
        options: [
          { value: 'Yes', label: 'Yes - Compatible with keyboards' },
          { value: 'No', label: 'No - Not compatible' },
        ],
        helpText: 'Can be used with external keyboards',
      },
      {
        name: 'warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
    ],
    speakers: [
      {
        name: 'speaker_type',
        label: 'Speaker Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Portable Bluetooth Speaker', label: 'Portable Bluetooth Speaker' },
          { value: 'Smart Speaker', label: 'Smart Speaker (Alexa/Google)' },
          { value: 'Home Theatre', label: 'Home Theatre' },
          { value: 'Soundbar', label: 'Soundbar' },
          { value: 'Studio Monitor', label: 'Studio Monitor' },
          { value: 'Party Speaker', label: 'Party Speaker' },
          { value: 'Bookshelf Speaker', label: 'Bookshelf Speaker' },
          { value: 'Car Speaker', label: 'Car Speaker' },
        ],
        helpText: 'Select the type of speaker',
      },
      {
        name: 'power_output',
        label: 'Power Output (Watts)',
        type: 'text',
        placeholder: 'e.g., 20W, 50W, 300W',
        helpText: 'Total power output in watts',
      },
      {
        name: 'driver_count',
        label: 'Number of Drivers',
        type: 'text',
        placeholder: 'e.g., 2, 3, 4',
        helpText: 'Number of speaker drivers',
      },
      {
        name: 'speaker_frequency_response',
        label: 'Frequency Response',
        type: 'text',
        placeholder: 'e.g., 20Hz – 20kHz',
        helpText: 'Audio frequency range',
      },
      {
        name: 'speaker_connectivity',
        label: 'Connectivity',
        type: 'textarea',
        placeholder: 'e.g., Bluetooth 5.1, Wi-Fi, USB, AUX (3.5mm), HDMI ARC, Optical, NFC',
        helpText: 'List all available connectivity options',
      },
      {
        name: 'waterproof_rating',
        label: 'Waterproof Rating',
        type: 'select',
        placeholder: 'Select rating',
        options: [
          { value: 'No Rating', label: 'No Rating' },
          { value: 'IPX4', label: 'IPX4 (Splash resistant)' },
          { value: 'IPX5', label: 'IPX5 (Water jet resistant)' },
          { value: 'IPX6', label: 'IPX6 (Powerful water jet resistant)' },
          { value: 'IP67', label: 'IP67 (Dust tight & submersible)' },
          { value: 'IP68', label: 'IP68 (Full submersible)' },
        ],
        helpText: 'Water and dust resistance rating',
      },
      {
        name: 'speaker_battery_capacity',
        label: 'Battery Capacity (mAh)',
        type: 'text',
        placeholder: 'e.g., 5000mAh, 10000mAh',
        helpText: 'For portable speakers only',
      },
      {
        name: 'battery_life_hours',
        label: 'Battery Life (Hours)',
        type: 'number',
        placeholder: 'e.g., 15',
        helpText: 'Approximate battery runtime in hours',
      },
      {
        name: 'speaker_charging_port',
        label: 'Charging Port',
        type: 'select',
        placeholder: 'Select charging port',
        options: [
          { value: 'USB-C', label: 'USB-C' },
          { value: 'Micro-USB', label: 'Micro-USB' },
          { value: 'Proprietary Port', label: 'Proprietary Port' },
          { value: 'Not Applicable', label: 'N/A (Passive Speaker)' },
        ],
        helpText: 'Type of charging port (optional)',
      },
      {
        name: 'speaker_weight',
        label: 'Weight',
        type: 'text',
        placeholder: 'e.g., 950g or 2.1kg',
        helpText: 'Speaker weight in grams or kilograms',
      },
      {
        name: 'speaker_special_features',
        label: 'Special Features',
        type: 'textarea',
        placeholder: 'e.g., RGB Lighting, Built-in Microphone, Powerbank Function, Multi-room Audio, Surround Sound, Voice Assistant, Remote Control, NFC Pairing',
        helpText: 'List any special features (optional)',
      },
      {
        name: 'warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
    ],
    power_banks: [
      {
        name: 'capacity_mah',
        label: 'Capacity (mAh)',
        type: 'text',
        required: true,
        placeholder: 'e.g., 10000, 20000, 30000, 50000',
        helpText: 'Power bank capacity in milliamp-hours',
      },
      {
        name: 'output_ports',
        label: 'Output Ports',
        type: 'textarea',
        placeholder: 'e.g., 2x USB-A, 1x USB-C PD, 1x Micro USB',
        helpText: 'List all available output ports and types',
      },
      {
        name: 'input_charging_options',
        label: 'Input Charging Options',
        type: 'textarea',
        placeholder: 'e.g., USB-C, Micro USB, Lightning',
        helpText: 'Available input charging methods',
      },
      {
        name: 'fast_charging_support',
        label: 'Fast Charging Support',
        type: 'select',
        required: true,
        placeholder: 'Select fast charging standard',
        options: [
          { value: 'No Fast Charging', label: 'No Fast Charging' },
          { value: '10W Fast Charging', label: '10W Fast Charging' },
          { value: '18W Fast Charging', label: '18W Fast Charging (Quick Charge 3.0)' },
          { value: '20W PD', label: '20W PD (Power Delivery)' },
          { value: '30W PD', label: '30W PD' },
          { value: '45W Super Fast Charging', label: '45W Super Fast Charging' },
          { value: '65W Laptop Charging', label: '65W Laptop Charging' },
          { value: '100W High-Speed PD', label: '100W High-Speed PD' },
        ],
        helpText: 'Maximum fast charging speed standard',
      },
      {
        name: 'powerbank_battery_type',
        label: 'Battery Type',
        type: 'select',
        required: true,
        placeholder: 'Select battery type',
        options: [
          { value: 'Lithium-ion', label: 'Lithium-ion (Li-ion)' },
          { value: 'Lithium Polymer', label: 'Lithium Polymer (Li-Po)' },
        ],
        helpText: 'Battery chemistry (important for safety and quality)',
      },
      {
        name: 'led_display',
        label: 'LED Display',
        type: 'select',
        required: true,
        placeholder: 'Select display type',
        options: [
          { value: 'Yes', label: 'Yes - Has LED/Digital display' },
          { value: 'No', label: 'No - No display' },
        ],
        helpText: 'LED or digital display for battery percentage',
      },
      {
        name: 'powerbank_special_features',
        label: 'Special Features',
        type: 'textarea',
        placeholder: 'e.g., Wireless Charging (15W Qi), Pass-through charging, Built-in cables, Torchlight, Overcharge protection, Temperature control, Short-circuit protection',
        helpText: 'List any special features or safety features (optional)',
      },
      {
        name: 'powerbank_weight_grams',
        label: 'Weight (grams)',
        type: 'text',
        placeholder: 'e.g., 300g, 450g',
        helpText: 'Weight in grams',
      },
      {
        name: 'powerbank_dimensions',
        label: 'Dimensions',
        type: 'text',
        placeholder: 'e.g., 150 × 75 × 25 mm',
        helpText: 'Product dimensions (optional)',
      },
      {
        name: 'warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
    ],
    microphones: [
      {
        name: 'microphone_type',
        label: 'Microphone Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Lavalier', label: 'Lavalier (Lapel)' },
          { value: 'Condenser', label: 'Condenser' },
          { value: 'Dynamic', label: 'Dynamic' },
          { value: 'Shotgun', label: 'Shotgun' },
          { value: 'USB Microphone', label: 'USB Microphone' },
          { value: 'Wireless', label: 'Wireless' },
          { value: 'Studio', label: 'Studio Microphone' },
          { value: 'Boundary', label: 'Boundary' },
        ],
        helpText: 'Type of microphone',
      },
      {
        name: 'polar_pattern',
        label: 'Polar Pattern',
        type: 'select',
        placeholder: 'Select pattern',
        options: [
          { value: 'Cardioid', label: 'Cardioid (Heart-shaped)' },
          { value: 'Omnidirectional', label: 'Omnidirectional (All directions)' },
          { value: 'Bidirectional', label: 'Bidirectional (Figure-8)' },
          { value: 'Super-cardioid', label: 'Super-cardioid' },
          { value: 'Hyper-cardioid', label: 'Hyper-cardioid' },
        ],
        helpText: 'Sound pickup pattern',
      },
      {
        name: 'microphone_frequency_response',
        label: 'Frequency Response',
        type: 'text',
        placeholder: 'e.g., 20Hz – 20kHz',
        helpText: 'Range of sound the microphone can capture',
      },
      {
        name: 'sensitivity',
        label: 'Sensitivity',
        type: 'text',
        placeholder: 'e.g., -38dB ± 3dB',
        helpText: 'Microphone sensitivity rating',
      },
      {
        name: 'mic_connectivity',
        label: 'Connectivity',
        type: 'select',
        required: true,
        placeholder: 'Select connection type',
        options: [
          { value: '3.5mm Jack', label: '3.5mm Jack (Aux)' },
          { value: 'USB', label: 'USB' },
          { value: 'USB-C', label: 'USB-C' },
          { value: 'XLR', label: 'XLR' },
          { value: 'Lightning', label: 'Lightning' },
          { value: 'Wireless 2.4GHz', label: 'Wireless 2.4GHz' },
          { value: 'Bluetooth', label: 'Bluetooth' },
          { value: 'Multi-pin', label: 'Multi-pin Connector' },
        ],
        helpText: 'Connection type to device',
      },
      {
        name: 'power_requirement',
        label: 'Power Requirement',
        type: 'select',
        placeholder: 'Select power type',
        options: [
          { value: 'Battery Powered', label: 'Battery Powered' },
          { value: 'Phantom Power 48V', label: 'Phantom Power 48V' },
          { value: 'USB Powered', label: 'USB Powered' },
          { value: 'Passive (No Power)', label: 'Passive (No Power)' },
          { value: 'Plugin Power', label: 'Plugin Power' },
        ],
        helpText: 'Power source required',
      },
      {
        name: 'cable_length_meters',
        label: 'Cable Length (Meters)',
        type: 'text',
        placeholder: 'e.g., 1.5m, 6m, 10m',
        helpText: 'Cable length (for wired microphones)',
      },
      {
        name: 'mic_weight_grams',
        label: 'Weight (grams)',
        type: 'text',
        placeholder: 'e.g., 150g, 250g',
        helpText: 'Microphone weight in grams',
      },
      {
        name: 'warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
    ],
    televisions: [
      {
        name: 'screen_size_inches',
        label: 'Screen Size (inches)',
        type: 'text',
        required: true,
        placeholder: 'e.g., 32, 43, 55, 65, 75, 85',
        helpText: 'Diagonal screen size in inches',
      },
      {
        name: 'tv_resolution',
        label: 'Display Resolution',
        type: 'select',
        required: true,
        placeholder: 'Select resolution',
        options: [
          { value: '720p', label: '720p (HD)' },
          { value: '1080p', label: '1080p (Full HD)' },
          { value: '4K UHD', label: '4K UHD (3840 × 2160)' },
          { value: '8K', label: '8K (7680 × 4320)' },
        ],
        helpText: 'TV resolution and clarity',
      },
      {
        name: 'display_technology',
        label: 'Display Technology',
        type: 'select',
        required: true,
        placeholder: 'Select technology',
        options: [
          { value: 'LED', label: 'LED' },
          { value: 'OLED', label: 'OLED (Organic LED)' },
          { value: 'QLED', label: 'QLED (Samsung)' },
          { value: 'Mini-LED', label: 'Mini-LED' },
          { value: 'Plasma', label: 'Plasma (Rare)' },
        ],
        helpText: 'Panel technology used',
      },
      {
        name: 'is_smart_tv',
        label: 'Smart TV',
        type: 'select',
        required: true,
        placeholder: 'Select option',
        options: [
          { value: 'Yes', label: 'Yes - Smart TV' },
          { value: 'No', label: 'No - Non-Smart TV' },
        ],
        helpText: 'Does it have smart features?',
      },
      {
        name: 'operating_system_tv',
        label: 'Operating System (if Smart TV)',
        type: 'select',
        placeholder: 'Select OS',
        options: [
          { value: 'WebOS', label: 'WebOS (LG)' },
          { value: 'Android TV', label: 'Android TV' },
          { value: 'Tizen', label: 'Tizen (Samsung)' },
          { value: 'Roku', label: 'Roku' },
          { value: 'Fire TV', label: 'Fire TV (Amazon)' },
          { value: 'Proprietary', label: 'Proprietary OS' },
          { value: 'N/A', label: 'N/A (Non-Smart)' },
        ],
        helpText: 'Smart TV operating system',
      },
      {
        name: 'refresh_rate_tv',
        label: 'Refresh Rate',
        type: 'select',
        placeholder: 'Select refresh rate',
        options: [
          { value: '60Hz', label: '60Hz' },
          { value: '120Hz', label: '120Hz' },
          { value: '144Hz', label: '144Hz' },
          { value: 'Variable', label: 'Variable Refresh Rate (VRR)' },
        ],
        helpText: 'Screen refresh rate (Hz)',
      },
      {
        name: 'screen_type',
        label: 'Screen Type',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'Flat', label: 'Flat' },
          { value: 'Curved', label: 'Curved' },
        ],
        helpText: 'Flat or curved screen design',
      },
      {
        name: 'tv_connectivity',
        label: 'Connectivity',
        type: 'textarea',
        placeholder: 'e.g., Wi-Fi (2.4GHz/5GHz), Bluetooth 5.0, HDMI 2.1 x3, USB x2, Optical Audio, Ethernet',
        helpText: 'List all available connectivity options',
      },
      {
        name: 'hdr_support',
        label: 'HDR Support',
        type: 'select',
        placeholder: 'Select HDR types',
        options: [
          { value: 'None', label: 'None' },
          { value: 'HDR10', label: 'HDR10' },
          { value: 'Dolby Vision', label: 'Dolby Vision' },
          { value: 'HDR10 + Dolby Vision', label: 'HDR10 + Dolby Vision' },
          { value: 'HDR10 + HLG', label: 'HDR10 + HLG' },
          { value: 'Full HDR', label: 'Full HDR (All formats)' },
        ],
        helpText: 'High Dynamic Range support formats',
      },
      {
        name: 'power_consumption_watts',
        label: 'Power Consumption (Watts)',
        type: 'text',
        placeholder: 'e.g., 150W, 200W',
        helpText: 'Typical power consumption (optional)',
      },
      {
        name: 'speaker_output',
        label: 'Speaker Output',
        type: 'text',
        placeholder: 'e.g., 20W (10W × 2), 40W Dolby Atmos',
        helpText: 'Built-in speaker power output',
      },
      {
        name: 'tv_warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
    ],
    networking: [
      {
        name: 'device_type',
        label: 'Device Type',
        type: 'select',
        required: true,
        placeholder: 'Select device type',
        options: [
          { value: 'Router', label: 'Router / Modem' },
          { value: 'MiFi', label: 'MiFi / Mobile Hotspot' },
          { value: 'Switch', label: 'Network Switch' },
          { value: 'Access Point', label: 'Access Point' },
          { value: 'Other', label: 'Other Device' },
        ],
        helpText: 'Type of networking device',
      },
      {
        name: 'networking_brand',
        label: 'Brand',
        type: 'text',
        required: true,
        placeholder: 'e.g., TP-Link, D-Link, Huawei',
        helpText: 'Manufacturer name',
      },
      {
        name: 'model_number_network',
        label: 'Model Number',
        type: 'text',
        required: true,
        placeholder: 'e.g., Archer C6, DIR-882',
        helpText: 'Device model number',
      },
      {
        name: 'wifi_standard',
        label: 'Wi-Fi Standard',
        type: 'select',
        placeholder: 'Select standard',
        options: [
          { value: '802.11b', label: '802.11b (11 Mbps)' },
          { value: '802.11g', label: '802.11g (54 Mbps)' },
          { value: '802.11n', label: '802.11n (Wi-Fi 4)' },
          { value: '802.11ac', label: '802.11ac (Wi-Fi 5)' },
          { value: '802.11ax', label: '802.11ax (Wi-Fi 6)' },
          { value: '802.11be', label: '802.11be (Wi-Fi 7)' },
          { value: 'N/A', label: 'N/A (Non-WiFi)' },
        ],
        helpText: 'Wi-Fi standard supported',
      },
      {
        name: 'network_speed_mbps',
        label: 'Maximum Speed (Mbps)',
        type: 'text',
        placeholder: 'e.g., 1200, 5400, 12000',
        helpText: 'Maximum throughput in Mbps',
      },
      {
        name: 'ethernet_ports',
        label: 'Ethernet Ports',
        type: 'number',
        placeholder: '4',
        helpText: 'Number of wired LAN ports',
      },
      {
        name: 'wireless_bands',
        label: 'Wireless Bands',
        type: 'select',
        placeholder: 'Select bands',
        options: [
          { value: '2.4GHz only', label: '2.4GHz only' },
          { value: '5GHz only', label: '5GHz only' },
          { value: '2.4GHz + 5GHz', label: 'Dual Band (2.4GHz + 5GHz)' },
          { value: '2.4GHz + 5GHz + 6GHz', label: 'Tri Band (2.4GHz + 5GHz + 6GHz)' },
        ],
        helpText: 'Frequency bands available',
      },
      {
        name: 'network_connectivity',
        label: 'Connectivity & Features',
        type: 'textarea',
        placeholder: 'e.g., USB 3.0, HDMI, VPN support, Parental controls, Cloud services',
        helpText: 'List available connectivity options and features',
      },
      {
        name: 'network_warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
    ],
    cctv: [
      {
        name: 'cctv_device_type',
        label: 'Device Type',
        type: 'select',
        required: true,
        placeholder: 'Select device type',
        options: [
          { value: 'Camera Only', label: 'Camera Only' },
          { value: 'DVR System', label: 'DVR System (Complete Package)' },
          { value: 'NVR System', label: 'NVR System (Complete Package)' },
          { value: 'Standalone NVR', label: 'Standalone NVR' },
          { value: 'Cables & Accessories', label: 'Cables & Accessories' },
        ],
        helpText: 'Type of CCTV/Security device',
      },
      {
        name: 'cctv_brand',
        label: 'Brand',
        type: 'text',
        required: true,
        placeholder: 'e.g., Hikvision, Dahua, Reolink',
        helpText: 'Manufacturer name',
      },
      {
        name: 'camera_type_cctv',
        label: 'Camera Type',
        type: 'select',
        placeholder: 'Select camera type',
        options: [
          { value: 'Bullet', label: 'Bullet Camera' },
          { value: 'Dome', label: 'Dome Camera' },
          { value: 'Turret', label: 'Turret Camera' },
          { value: 'PTZ', label: 'PTZ (Pan-Tilt-Zoom)' },
          { value: 'Fisheye', label: 'Fisheye / 360°' },
          { value: 'Hidden', label: 'Hidden / Covert' },
        ],
        helpText: 'Physical camera form factor',
      },
      {
        name: 'cctv_resolution',
        label: 'Video Resolution',
        type: 'select',
        placeholder: 'Select resolution',
        options: [
          { value: '720p', label: '720p (1280 × 720)' },
          { value: '1080p', label: '1080p (1920 × 1080)' },
          { value: '2MP', label: '2MP (1920 × 1080)' },
          { value: '3MP', label: '3MP (2048 × 1536)' },
          { value: '4MP', label: '4MP (2560 × 1440)' },
          { value: '5MP', label: '5MP (2560 × 1920)' },
          { value: '8MP', label: '8MP (3840 × 2160)' },
        ],
        helpText: 'Maximum video recording resolution',
      },
      {
        name: 'cctv_connectivity',
        label: 'Connectivity',
        type: 'select',
        placeholder: 'Select connectivity',
        options: [
          { value: 'Wired (Coax)', label: 'Wired Coaxial' },
          { value: 'Wired (RJ45)', label: 'Wired Ethernet (RJ45)' },
          { value: 'WiFi', label: 'Wi-Fi' },
          { value: 'Mixed', label: 'Wired + Wi-Fi' },
        ],
        helpText: 'How camera connects to system',
      },
      {
        name: 'cctv_night_vision',
        label: 'Night Vision',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'None', label: 'None' },
          { value: 'IR LED', label: 'Infrared LED (IR)' },
          { value: 'Thermal', label: 'Thermal' },
          { value: 'Low Light', label: 'Low Light Enhanced' },
        ],
        helpText: 'Low-light/nighttime capability',
      },
      {
        name: 'number_of_cameras',
        label: 'Number of Cameras (if package)',
        type: 'number',
        placeholder: '4',
        helpText: 'For system packages, how many cameras included',
      },
      {
        name: 'storage_type_cctv',
        label: 'Storage Method',
        type: 'select',
        placeholder: 'Select storage',
        options: [
          { value: 'Local HDD', label: 'Local Hard Drive (DVR/NVR)' },
          { value: 'Cloud', label: 'Cloud Storage' },
          { value: 'Local + Cloud', label: 'Local + Cloud' },
          { value: 'SD Card', label: 'SD Card' },
          { value: 'Other', label: 'Other' },
        ],
        helpText: 'Where recordings are stored',
      },
      {
        name: 'cctv_features',
        label: 'Special Features',
        type: 'textarea',
        placeholder: 'e.g., Motion detection, Person detection, Smart analytics, Mobile app, ONVIF compatible',
        helpText: 'List available features and capabilities',
      },
      {
        name: 'cctv_warranty_months',
        label: 'Warranty Period (Months)',
        type: 'number',
        placeholder: '12',
        helpText: 'Warranty duration in months',
      },
    ],
  },
  appliances: {
    refrigerators: [
      // CORE FIELDS
      {
        name: 'fridge_type',
        label: 'Refrigerator Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Single Door', label: 'Single Door' },
          { value: 'Double Door', label: 'Double Door' },
          { value: 'Deep Freezer', label: 'Deep Freezer' },
          { value: 'Chest Freezer', label: 'Chest Freezer' },
          { value: 'Side-by-Side', label: 'Side-by-Side' },
          { value: 'French Door', label: 'French Door' },
          { value: 'Wine Cooler', label: 'Wine Cooler' },
        ],
      },
      {
        name: 'capacity_liters',
        label: 'Capacity (Liters)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 450',
      },
      {
        name: 'energy_rating',
        label: 'Energy Rating',
        type: 'select',
        required: true,
        placeholder: 'Select rating',
        options: [
          { value: '1 Star', label: '1 Star' },
          { value: '2 Star', label: '2 Star' },
          { value: '3 Star', label: '3 Star' },
          { value: '4 Star', label: '4 Star' },
          { value: '5 Star', label: '5 Star' },
        ],
      },
      {
        name: 'cooling_technology',
        label: 'Cooling Technology',
        type: 'select',
        required: true,
        placeholder: 'Select technology',
        options: [
          { value: 'Direct Cool', label: 'Direct Cool' },
          { value: 'Frost-Free', label: 'Frost-Free' },
          { value: 'Inverter', label: 'Inverter' },
        ],
      },
      // BUILD & FEATURES
      {
        name: 'compressor_type',
        label: 'Compressor Type',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'Inverter', label: 'Inverter' },
          { value: 'Non-Inverter', label: 'Non-Inverter' },
        ],
      },
      {
        name: 'temperature_control',
        label: 'Temperature Control',
        type: 'select',
        placeholder: 'Select control type',
        options: [
          { value: 'Manual', label: 'Manual' },
          { value: 'Digital', label: 'Digital' },
        ],
      },
      {
        name: 'number_of_shelves',
        label: 'Number of Shelves',
        type: 'number',
        placeholder: 'e.g., 4',
      },
      {
        name: 'number_of_drawers',
        label: 'Number of Drawers',
        type: 'number',
        placeholder: 'e.g., 2',
      },
      {
        name: 'door_lock',
        label: 'Door Lock',
        type: 'select',
        placeholder: 'Has door lock?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'interior_light',
        label: 'Interior Light',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'LED', label: 'LED' },
          { value: 'Bulb', label: 'Bulb' },
          { value: 'None', label: 'None' },
        ],
      },
      {
        name: 'defrost_type',
        label: 'Defrost Type',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'Automatic', label: 'Automatic' },
          { value: 'Manual', label: 'Manual' },
        ],
      },
      {
        name: 'water_dispenser',
        label: 'Water Dispenser',
        type: 'select',
        placeholder: 'Has water dispenser?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'ice_maker',
        label: 'Ice Maker',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'Automatic', label: 'Automatic' },
          { value: 'Manual', label: 'Manual' },
          { value: 'None', label: 'None' },
        ],
      },
      // DIMENSIONS
      {
        name: 'height_cm',
        label: 'Height (cm)',
        type: 'number',
        placeholder: 'e.g., 170',
      },
      {
        name: 'width_cm',
        label: 'Width (cm)',
        type: 'number',
        placeholder: 'e.g., 70',
      },
      {
        name: 'depth_cm',
        label: 'Depth (cm)',
        type: 'number',
        placeholder: 'e.g., 65',
      },
      {
        name: 'weight_kg',
        label: 'Weight (kg)',
        type: 'number',
        placeholder: 'e.g., 85',
      },
      // OTHER
      {
        name: 'power_consumption_watts',
        label: 'Power Consumption (W)',
        type: 'number',
        placeholder: 'e.g., 150',
      },
      {
        name: 'noise_level_db',
        label: 'Noise Level (dB)',
        type: 'number',
        placeholder: 'e.g., 45',
      },
      {
        name: 'warranty_months',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12',
      },
    ],
    ac: [
      // CORE FIELDS
      {
        name: 'ac_type',
        label: 'AC Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Split Unit', label: 'Split Unit' },
          { value: 'Standing/Portable', label: 'Standing/Portable' },
          { value: 'Window', label: 'Window' },
          { value: 'Cassette', label: 'Cassette' },
          { value: 'Inverter', label: 'Inverter' },
        ],
      },
      {
        name: 'capacity_hp',
        label: 'Capacity (HP)',
        type: 'select',
        required: true,
        placeholder: 'Select capacity',
        options: [
          { value: '0.75', label: '0.75 HP' },
          { value: '1', label: '1 HP' },
          { value: '1.5', label: '1.5 HP' },
          { value: '2', label: '2 HP' },
          { value: '2.5', label: '2.5 HP' },
          { value: '3', label: '3 HP' },
        ],
      },
      {
        name: 'btu_rating',
        label: 'BTU Rating',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12000',
      },
      {
        name: 'cooling_technology_ac',
        label: 'Cooling Technology',
        type: 'select',
        required: true,
        placeholder: 'Select technology',
        options: [
          { value: 'Inverter', label: 'Inverter' },
          { value: 'Non-Inverter', label: 'Non-Inverter' },
        ],
      },
      // PERFORMANCE
      {
        name: 'air_flow_rate',
        label: 'Air Flow Rate (m³/min)',
        type: 'number',
        placeholder: 'e.g., 450',
      },
      {
        name: 'energy_efficiency_rating',
        label: 'Energy Efficiency Rating',
        type: 'select',
        placeholder: 'Select rating',
        options: [
          { value: '3 Star', label: '3 Star' },
          { value: '4 Star', label: '4 Star' },
          { value: '5 Star', label: '5 Star' },
        ],
      },
      {
        name: 'noise_level_ac_db',
        label: 'Noise Level (dB)',
        type: 'number',
        placeholder: 'e.g., 22',
      },
      // FEATURES
      {
        name: 'remote_control',
        label: 'Remote Control',
        type: 'select',
        placeholder: 'Has remote?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'sleep_mode',
        label: 'Sleep Mode',
        type: 'select',
        placeholder: 'Has sleep mode?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'turbo_mode',
        label: 'Turbo Mode',
        type: 'select',
        placeholder: 'Has turbo mode?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'anti_dust_filter',
        label: 'Anti-Dust Filter',
        type: 'select',
        placeholder: 'Has filter?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'auto_restart',
        label: 'Auto Restart',
        type: 'select',
        placeholder: 'Has auto restart?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      // INSTALLATION
      {
        name: 'indoor_unit_dimensions',
        label: 'Indoor Unit Dimensions',
        type: 'text',
        placeholder: 'e.g., 77 x 22 x 19 cm',
      },
      {
        name: 'outdoor_unit_dimensions',
        label: 'Outdoor Unit Dimensions',
        type: 'text',
        placeholder: 'e.g., 95 x 38 x 32 cm',
      },
      {
        name: 'refrigerant_type',
        label: 'Refrigerant Type',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'R22', label: 'R22' },
          { value: 'R410A', label: 'R410A' },
          { value: 'R32', label: 'R32' },
        ],
      },
      // OTHER
      {
        name: 'power_consumption_ac_watts',
        label: 'Power Consumption (W)',
        type: 'number',
        placeholder: 'e.g., 1200',
      },
      {
        name: 'warranty_months_ac',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12',
      },
    ],
    generators: [
      // CORE FIELDS
      {
        name: 'generator_type',
        label: 'Generator Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Petrol', label: 'Petrol' },
          { value: 'Diesel', label: 'Diesel' },
          { value: 'Inverter', label: 'Inverter' },
        ],
      },
      {
        name: 'rated_power_output',
        label: 'Rated Power Output (kVA)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 2.5',
        step: 0.1,
      },
      {
        name: 'maximum_output',
        label: 'Maximum Output (kVA)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 3',
      },
      {
        name: 'phase',
        label: 'Phase',
        type: 'select',
        placeholder: 'Select phase',
        options: [
          { value: 'Single', label: 'Single Phase' },
          { value: 'Three', label: 'Three Phase' },
        ],
      },
      // ENGINE DETAILS
      {
        name: 'engine_type',
        label: 'Engine Type',
        type: 'text',
        placeholder: 'e.g., Gasoline, Air-Cooled',
      },
      {
        name: 'engine_displacement_cc',
        label: 'Engine Displacement (cc)',
        type: 'number',
        placeholder: 'e.g., 389',
      },
      {
        name: 'starting_system',
        label: 'Starting System',
        type: 'select',
        required: true,
        placeholder: 'Select starting system',
        options: [
          { value: 'Manual', label: 'Manual' },
          { value: 'Electric', label: 'Electric' },
          { value: 'Recoil', label: 'Recoil' },
        ],
      },
      {
        name: 'fuel_tank_capacity_liters',
        label: 'Fuel Tank Capacity (Liters)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 15',
      },
      {
        name: 'fuel_consumption_lhr',
        label: 'Fuel Consumption (L/hr)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 1.5',
        step: 0.1,
      },
      // PERFORMANCE
      {
        name: 'runtime_full_tank_hours',
        label: 'Runtime per Full Tank (Hours)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 8',
      },
      {
        name: 'noise_level_gen_db',
        label: 'Noise Level (dB)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 70',
      },
      {
        name: 'coil_type',
        label: 'Coil Type',
        type: 'select',
        required: true,
        placeholder: 'Select coil type',
        options: [
          { value: 'Copper', label: 'Copper' },
          { value: 'Aluminum', label: 'Aluminum' },
        ],
      },
      // OTHER
      {
        name: 'battery_included',
        label: 'Battery Included',
        type: 'select',
        placeholder: 'Is battery included?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'portability',
        label: 'Portability',
        type: 'select',
        placeholder: 'Has wheels/handles?',
        options: [
          { value: 'Wheels', label: 'Wheels' },
          { value: 'Handles', label: 'Handles' },
          { value: 'Both', label: 'Both' },
          { value: 'None', label: 'None' },
        ],
      },
      {
        name: 'warranty_months_gen',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12',
      },
    ],
    washing_machines: [
      // CORE FIELDS
      {
        name: 'washer_type',
        label: 'Machine Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Top Load', label: 'Top Load' },
          { value: 'Front Load', label: 'Front Load' },
          { value: 'Washer-Dryer Combo', label: 'Washer-Dryer Combo' },
          { value: 'Dryer', label: 'Dryer Only' },
          { value: 'Mini Washer', label: 'Mini Washer' },
        ],
      },
      {
        name: 'wash_capacity_kg',
        label: 'Wash Capacity (kg)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 7',
      },
      {
        name: 'dry_capacity_kg',
        label: 'Dry Capacity (kg)',
        type: 'number',
        placeholder: 'e.g., 6 (if combo)',
      },
      // PERFORMANCE
      {
        name: 'spin_speed_rpm',
        label: 'Spin Speed (RPM)',
        type: 'number',
        placeholder: 'e.g., 800',
      },
      {
        name: 'number_of_wash_programs',
        label: 'Number of Wash Programs',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12',
      },
      {
        name: 'water_consumption_lpd',
        label: 'Water Consumption (L per wash)',
        type: 'number',
        placeholder: 'e.g., 40',
      },
      {
        name: 'energy_efficiency_washer',
        label: 'Energy Efficiency',
        type: 'select',
        placeholder: 'Select rating',
        options: [
          { value: '3 Star', label: '3 Star' },
          { value: '4 Star', label: '4 Star' },
          { value: '5 Star', label: '5 Star' },
        ],
      },
      {
        name: 'noise_level_wash_db',
        label: 'Noise Level (dB)',
        type: 'number',
        placeholder: 'e.g., 72',
      },
      // FEATURES
      {
        name: 'inverter_motor',
        label: 'Inverter Motor',
        type: 'select',
        placeholder: 'Has inverter motor?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'child_lock',
        label: 'Child Lock',
        type: 'select',
        placeholder: 'Has child lock?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'delay_timer',
        label: 'Delay Timer',
        type: 'select',
        placeholder: 'Has delay timer?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'temperature_control_wash',
        label: 'Temperature Control',
        type: 'select',
        placeholder: 'Has temp control?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'display_type_wash',
        label: 'Display Type',
        type: 'select',
        placeholder: 'Select display type',
        options: [
          { value: 'LED', label: 'LED' },
          { value: 'LCD', label: 'LCD' },
          { value: 'Mechanical', label: 'Mechanical' },
        ],
      },
      // DIMENSIONS
      {
        name: 'height_washer_cm',
        label: 'Height (cm)',
        type: 'number',
        placeholder: 'e.g., 85',
      },
      {
        name: 'width_washer_cm',
        label: 'Width (cm)',
        type: 'number',
        placeholder: 'e.g., 60',
      },
      {
        name: 'depth_washer_cm',
        label: 'Depth (cm)',
        type: 'number',
        placeholder: 'e.g., 65',
      },
      {
        name: 'warranty_months_wash',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 24',
      },
    ],
    cookers_ovens: [
      // CORE FIELDS
      {
        name: 'cooker_type',
        label: 'Cooker Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Gas', label: 'Gas Cooker' },
          { value: 'Electric', label: 'Electric Cooker' },
          { value: 'Dual', label: 'Dual (Gas + Electric)' },
        ],
      },
      {
        name: 'number_of_burners',
        label: 'Number of Burners',
        type: 'number',
        required: true,
        placeholder: 'e.g., 4',
      },
      {
        name: 'oven_type',
        label: 'Oven Type',
        type: 'select',
        required: true,
        placeholder: 'Select oven type',
        options: [
          { value: 'Gas', label: 'Gas Oven' },
          { value: 'Electric', label: 'Electric Oven' },
          { value: 'None', label: 'No Oven' },
        ],
      },
      {
        name: 'oven_capacity_liters',
        label: 'Oven Capacity (Liters)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 50',
      },
      // PERFORMANCE
      {
        name: 'ignition_type',
        label: 'Ignition Type',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'Manual', label: 'Manual' },
          { value: 'Automatic', label: 'Automatic' },
        ],
      },
      {
        name: 'grill_function',
        label: 'Grill Function',
        type: 'select',
        placeholder: 'Has grill?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'thermostat_control',
        label: 'Thermostat Control',
        type: 'select',
        placeholder: 'Has thermostat?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      // FEATURES
      {
        name: 'timer',
        label: 'Timer',
        type: 'select',
        placeholder: 'Has timer?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'oven_light',
        label: 'Oven Light',
        type: 'select',
        placeholder: 'Has oven light?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'safety_valve',
        label: 'Safety Valve',
        type: 'select',
        placeholder: 'Has safety valve?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'rotisserie',
        label: 'Rotisserie',
        type: 'select',
        placeholder: 'Has rotisserie?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      // DIMENSIONS
      {
        name: 'height_cooker_cm',
        label: 'Height (cm)',
        type: 'number',
        placeholder: 'e.g., 90',
      },
      {
        name: 'width_cooker_cm',
        label: 'Width (cm)',
        type: 'number',
        placeholder: 'e.g., 50',
      },
      {
        name: 'depth_cooker_cm',
        label: 'Depth (cm)',
        type: 'number',
        placeholder: 'e.g., 60',
      },
      // OTHER
      {
        name: 'power_consumption_cooker_watts',
        label: 'Power Consumption (W)',
        type: 'number',
        placeholder: 'e.g., 4000',
      },
      {
        name: 'warranty_months_cooker',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12',
      },
    ],
    cleaning_appliances: [
      // CORE FIELDS
      {
        name: 'vacuum_type',
        label: 'Vacuum Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Handheld', label: 'Handheld' },
          { value: 'Upright', label: 'Upright' },
          { value: 'Canister', label: 'Canister' },
          { value: 'Stick', label: 'Stick' },
          { value: 'Robotic', label: 'Robotic' },
          { value: 'Steam Mop', label: 'Steam Mop' },
          { value: 'Carpet Cleaner', label: 'Carpet Cleaner' },
        ],
      },
      {
        name: 'power_watts_clean',
        label: 'Power (W)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 1200',
      },
      {
        name: 'suction_power_aW',
        label: 'Suction Power (aW)',
        type: 'number',
        placeholder: 'e.g., 180',
      },
      // BUILD & FEATURES
      {
        name: 'dust_tank_capacity_liters',
        label: 'Dust Tank Capacity (Liters)',
        type: 'number',
        placeholder: 'e.g., 2',
      },
      {
        name: 'cord_length_or_battery_capacity',
        label: 'Cord Length (m) / Battery Capacity (mAh)',
        type: 'text',
        placeholder: 'e.g., 5m or 2500mAh',
      },
      {
        name: 'hepa_filter',
        label: 'HEPA Filter',
        type: 'select',
        placeholder: 'Has HEPA filter?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'multi_surface_brush',
        label: 'Multi-Surface Brush',
        type: 'select',
        placeholder: 'Has multi-surface brush?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'noise_level_clean_db',
        label: 'Noise Level (dB)',
        type: 'number',
        placeholder: 'e.g., 75',
      },
      // DIMENSIONS
      {
        name: 'weight_clean_kg',
        label: 'Weight (kg)',
        type: 'number',
        placeholder: 'e.g., 4.5',
      },
      {
        name: 'dimensions_clean',
        label: 'Dimensions (L x W x H cm)',
        type: 'text',
        placeholder: 'e.g., 30 x 25 x 110',
      },
      // OTHER
      {
        name: 'warranty_months_clean',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 24',
      },
    ],
    fans_cooling: [
      // CORE FIELDS
      {
        name: 'fan_type',
        label: 'Fan Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Standing Fan', label: 'Standing Fan' },
          { value: 'Rechargeable', label: 'Rechargeable Fan' },
          { value: 'Ceiling Fan', label: 'Ceiling Fan' },
          { value: 'Industrial', label: 'Industrial Fan' },
          { value: 'Mist Fan', label: 'Mist/Water Fan' },
        ],
      },
      {
        name: 'power_watts_fan',
        label: 'Power (W)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 60',
      },
      {
        name: 'blade_size_inches',
        label: 'Blade Size (Inches)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 16',
      },
      // PERFORMANCE
      {
        name: 'speed_levels',
        label: 'Speed Levels',
        type: 'select',
        placeholder: 'Number of speeds',
        options: [
          { value: '1', label: '1 Speed' },
          { value: '2', label: '2 Speeds' },
          { value: '3', label: '3 Speeds' },
          { value: '4', label: '4 Speeds' },
          { value: '5+', label: '5+ Speeds' },
        ],
      },
      {
        name: 'airflow_rate_cmm',
        label: 'Airflow Rate (m³/min)',
        type: 'number',
        placeholder: 'e.g., 150',
      },
      {
        name: 'tilting_adjustment',
        label: 'Tilting Adjustment',
        type: 'select',
        placeholder: 'Has tilting?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      // RECHARGEABLE FAN FIELDS
      {
        name: 'battery_capacity_mah',
        label: 'Battery Capacity (mAh)',
        type: 'number',
        placeholder: 'e.g., 2500 (if rechargeable)',
      },
      {
        name: 'runtime_hours_fan',
        label: 'Runtime (Hours)',
        type: 'number',
        placeholder: 'e.g., 8',
      },
      {
        name: 'charging_time_hours',
        label: 'Charging Time (Hours)',
        type: 'number',
        placeholder: 'e.g., 4',
      },
      // OTHER
      {
        name: 'noise_level_fan_db',
        label: 'Noise Level (dB)',
        type: 'number',
        placeholder: 'e.g., 60',
      },
      {
        name: 'warranty_months_fan',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12',
      },
    ],
    inverter_solar: [
      // CORE FIELDS
      {
        name: 'solar_product_type',
        label: 'Product Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Inverter', label: 'Inverter' },
          { value: 'Solar Panel', label: 'Solar Panel' },
          { value: 'Charge Controller', label: 'Charge Controller' },
          { value: 'Battery', label: 'Battery' },
        ],
      },
      // INVERTER FIELDS
      {
        name: 'inverter_capacity_watts',
        label: 'Capacity (Watts)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 3000 (for 3kW)',
      },
      {
        name: 'battery_compatibility_inverter',
        label: 'Battery Compatibility',
        type: 'text',
        placeholder: 'e.g., 12V, 24V, 48V',
      },
      {
        name: 'input_voltage_inverter',
        label: 'Input Voltage',
        type: 'text',
        placeholder: 'e.g., 12V DC',
      },
      {
        name: 'output_voltage_inverter',
        label: 'Output Voltage',
        type: 'text',
        placeholder: 'e.g., 230V AC',
      },
      {
        name: 'inverter_efficiency_percent',
        label: 'Efficiency (%)',
        type: 'number',
        placeholder: 'e.g., 92',
        step: 0.1,
      },
      {
        name: 'display_type_inverter',
        label: 'Display Type',
        type: 'select',
        placeholder: 'Select display',
        options: [
          { value: 'LED', label: 'LED' },
          { value: 'LCD', label: 'LCD' },
          { value: 'Digital', label: 'Digital' },
          { value: 'None', label: 'None' },
        ],
      },
      // BATTERY FIELDS
      {
        name: 'battery_type',
        label: 'Battery Type',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'Lithium', label: 'Lithium' },
          { value: 'SMF', label: 'SMF (Sealed)' },
          { value: 'Gel', label: 'Gel' },
          { value: 'AGM', label: 'AGM' },
        ],
      },
      {
        name: 'battery_capacity_ah',
        label: 'Battery Capacity (Ah)',
        type: 'number',
        placeholder: 'e.g., 100',
      },
      {
        name: 'battery_voltage',
        label: 'Battery Voltage',
        type: 'select',
        placeholder: 'Select voltage',
        options: [
          { value: '12V', label: '12V' },
          { value: '24V', label: '24V' },
          { value: '48V', label: '48V' },
        ],
      },
      // SOLAR PANEL FIELDS
      {
        name: 'solar_wattage',
        label: 'Solar Panel Wattage (W)',
        type: 'number',
        placeholder: 'e.g., 400',
      },
      {
        name: 'solar_efficiency_percent',
        label: 'Efficiency (%)',
        type: 'number',
        placeholder: 'e.g., 21',
        step: 0.1,
      },
      {
        name: 'open_circuit_voltage',
        label: 'Open Circuit Voltage (Voc)',
        type: 'number',
        placeholder: 'e.g., 50',
      },
      {
        name: 'short_circuit_current',
        label: 'Short Circuit Current (Isc)',
        type: 'number',
        placeholder: 'e.g., 10',
      },
      // CHARGE CONTROLLER FIELDS
      {
        name: 'charge_controller_type',
        label: 'Charge Controller Type',
        type: 'select',
        placeholder: 'Select type',
        options: [
          { value: 'PWM', label: 'PWM' },
          { value: 'MPPT', label: 'MPPT' },
        ],
      },
      {
        name: 'controller_rating_amps',
        label: 'Rating (Amps)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 60',
      },
      // OTHER
      {
        name: 'warranty_months_solar',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 60',
      },
    ],
    kitchen_appliances: [
      // CORE FIELDS
      {
        name: 'kitchen_appliance_type',
        label: 'Appliance Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Blender', label: 'Blender' },
          { value: 'Electric Kettle', label: 'Electric Kettle' },
          { value: 'Rice Cooker', label: 'Rice Cooker' },
          { value: 'Juicer', label: 'Juicer' },
          { value: 'Mixer', label: 'Mixer' },
          { value: 'Coffee Maker', label: 'Coffee Maker' },
          { value: 'Sandwich Maker', label: 'Sandwich Maker' },
          { value: 'Microwave', label: 'Microwave Oven' },
          { value: 'Air Fryer', label: 'Air Fryer' },
          { value: 'Toaster', label: 'Toaster' },
        ],
      },
      {
        name: 'power_watts_kitchen',
        label: 'Power (Watts)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 600',
      },
      {
        name: 'capacity_kitchen',
        label: 'Capacity',
        type: 'text',
        required: true,
        placeholder: 'e.g., 1.5L or 2 cups',
      },
      // FEATURES
      {
        name: 'speed_levels_kitchen',
        label: 'Speed Levels',
        type: 'number',
        placeholder: 'e.g., 3',
      },
      {
        name: 'timer_kitchen',
        label: 'Timer',
        type: 'select',
        placeholder: 'Has timer?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'heating_function',
        label: 'Heating Function',
        type: 'select',
        placeholder: 'Has heating?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'safety_lock',
        label: 'Safety Lock',
        type: 'select',
        placeholder: 'Has safety lock?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'non_stick_coating',
        label: 'Non-Stick Coating',
        type: 'select',
        placeholder: 'Has non-stick?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
          { value: 'N/A', label: 'N/A' },
        ],
      },
      {
        name: 'display_type_kitchen',
        label: 'Display Type',
        type: 'select',
        placeholder: 'Select display',
        options: [
          { value: 'LED', label: 'LED' },
          { value: 'LCD', label: 'LCD' },
          { value: 'Mechanical', label: 'Mechanical' },
          { value: 'None', label: 'None' },
        ],
      },
      // OTHER
      {
        name: 'warranty_months_kitchen',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12',
      },
    ],
    home_appliances: [
      // CORE FIELDS
      {
        name: 'home_appliance_type',
        label: 'Appliance Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Dishwasher', label: 'Dishwasher' },
          { value: 'Water Dispenser', label: 'Water Dispenser' },
          { value: 'Electric Iron', label: 'Electric Iron' },
          { value: 'Hair Dryer', label: 'Hair Dryer' },
          { value: 'Humidifier', label: 'Humidifier' },
          { value: 'Dehumidifier', label: 'Dehumidifier' },
          { value: 'Other', label: 'Other' },
        ],
      },
      {
        name: 'power_watts_home',
        label: 'Power (Watts)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 1800',
      },
      {
        name: 'capacity_or_feature_home',
        label: 'Capacity/Special Feature',
        type: 'text',
        placeholder: 'e.g., 10L, Ionic Technology, etc.',
      },
      // FEATURES
      {
        name: 'temperature_control_home',
        label: 'Temperature Control',
        type: 'select',
        placeholder: 'Has temp control?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'timer_home',
        label: 'Timer',
        type: 'select',
        placeholder: 'Has timer?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'auto_shutoff',
        label: 'Auto Shutoff',
        type: 'select',
        placeholder: 'Has auto shutoff?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
      {
        name: 'display_type_home',
        label: 'Display Type',
        type: 'select',
        placeholder: 'Select display',
        options: [
          { value: 'LED', label: 'LED' },
          { value: 'LCD', label: 'LCD' },
          { value: 'Digital', label: 'Digital' },
          { value: 'Mechanical', label: 'Mechanical' },
          { value: 'None', label: 'None' },
        ],
      },
      {
        name: 'noise_level_home_db',
        label: 'Noise Level (dB)',
        type: 'number',
        placeholder: 'e.g., 60',
      },
      // DIMENSIONS
      {
        name: 'dimensions_home',
        label: 'Dimensions (L x W x H cm)',
        type: 'text',
        placeholder: 'e.g., 45 x 35 x 85',
      },
      {
        name: 'weight_home_kg',
        label: 'Weight (kg)',
        type: 'number',
        placeholder: 'e.g., 8',
      },
      // OTHER
      {
        name: 'warranty_months_home',
        label: 'Warranty (Months)',
        type: 'number',
        required: true,
        placeholder: 'e.g., 12',
      },
    ],
  },
  furniture: {
    sofas: [
      {
        name: 'seating_capacity',
        label: 'Seating Capacity',
        type: 'select',
        required: true,
        placeholder: 'Select capacity',
        options: [
          { value: '2-seater', label: '2-seater' },
          { value: '3-seater', label: '3-seater' },
          { value: '4-seater', label: '4-seater' },
          { value: '5-seater', label: '5-seater' },
          { value: 'Sectional', label: 'Sectional' },
        ],
      },
      {
        name: 'material',
        label: 'Material',
        type: 'select',
        required: true,
        placeholder: 'Select material',
        options: [
          { value: 'Leather', label: 'Leather' },
          { value: 'Fabric', label: 'Fabric' },
          { value: 'Suede', label: 'Suede' },
          { value: 'Microfiber', label: 'Microfiber' },
          { value: 'Velvet', label: 'Velvet' },
        ],
      },
      {
        name: 'color',
        label: 'Color',
        type: 'text',
        placeholder: 'e.g., Black, Cream, Navy Blue',
      },
      {
        name: 'width_cm',
        label: 'Width (cm)',
        type: 'number',
        placeholder: 'e.g., 200',
      },
      {
        name: 'depth_cm',
        label: 'Depth (cm)',
        type: 'number',
        placeholder: 'e.g., 85',
      },
      {
        name: 'reclining',
        label: 'Reclining Feature',
        type: 'select',
        placeholder: 'Has reclining?',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Manual', label: 'Manual' },
          { value: 'Electric', label: 'Electric' },
        ],
      },
    ],
    beds: [
      {
        name: 'bed_size',
        label: 'Bed Size',
        type: 'select',
        required: true,
        placeholder: 'Select size',
        options: [
          { value: 'Single', label: 'Single' },
          { value: 'Double', label: 'Double' },
          { value: 'Queen', label: 'Queen' },
          { value: 'King', label: 'King' },
          { value: 'Super King', label: 'Super King' },
        ],
      },
      {
        name: 'material',
        label: 'Frame Material',
        type: 'select',
        required: true,
        placeholder: 'Select material',
        options: [
          { value: 'Wood', label: 'Wood' },
          { value: 'Metal', label: 'Metal' },
          { value: 'Upholstered', label: 'Upholstered' },
          { value: 'Leather', label: 'Leather' },
        ],
      },
      {
        name: 'storage',
        label: 'Storage Options',
        type: 'select',
        placeholder: 'Select storage',
        options: [
          { value: 'None', label: 'None' },
          { value: 'Under-bed Drawers', label: 'Under-bed Drawers' },
          { value: 'Headboard Storage', label: 'Headboard Storage' },
        ],
      },
      {
        name: 'mattress_included',
        label: 'Mattress Included',
        type: 'select',
        placeholder: 'Includes mattress?',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes' },
        ],
      },
    ],
  },
  grocery: {
    produce: [
      {
        name: 'produce_type',
        label: 'Produce Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Fruits', label: 'Fruits' },
          { value: 'Vegetables', label: 'Vegetables' },
          { value: 'Leafy Greens', label: 'Leafy Greens' },
          { value: 'Roots & Tubers', label: 'Roots & Tubers' },
        ],
      },
      {
        name: 'origin',
        label: 'Origin/Source',
        type: 'text',
        placeholder: 'e.g., Local Farm, Imported',
      },
      {
        name: 'organic_certified',
        label: 'Organic Certified',
        type: 'select',
        placeholder: 'Is it organic?',
        options: [
          { value: 'No', label: 'No' },
          { value: 'Yes', label: 'Yes - Certified' },
        ],
      },
      {
        name: 'expiry_days',
        label: 'Shelf Life (Days)',
        type: 'number',
        placeholder: 'e.g., 7',
        helpText: 'Approximate days until expiry',
      },
    ],
    dairy: [
      {
        name: 'product_type',
        label: 'Product Type',
        type: 'select',
        required: true,
        placeholder: 'Select type',
        options: [
          { value: 'Milk', label: 'Milk' },
          { value: 'Cheese', label: 'Cheese' },
          { value: 'Yogurt', label: 'Yogurt' },
          { value: 'Butter', label: 'Butter' },
          { value: 'Eggs', label: 'Eggs' },
        ],
      },
      {
        name: 'fat_content',
        label: 'Fat Content',
        type: 'select',
        placeholder: 'Select fat content',
        options: [
          { value: 'Full Fat', label: 'Full Fat' },
          { value: 'Low Fat', label: 'Low Fat' },
          { value: 'Skimmed', label: 'Skimmed' },
        ],
      },
      {
        name: 'pasteurized',
        label: 'Pasteurized',
        type: 'select',
        placeholder: 'Is it pasteurized?',
        options: [
          { value: 'Yes', label: 'Yes' },
          { value: 'No', label: 'No' },
        ],
      },
    ],
  },
};

export const getSpecificationsByCategory = (category: string, subcategory: string): SpecField[] => {
  return PRODUCT_SPECIFICATIONS[category]?.[subcategory] || [];
};
